name: salah_silence_app
description: Auto-silence app during prayer times

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  flutter_background_service: ^5.0.5
  flutter_foreground_task: ^9.1.0
  shared_preferences: ^2.2.2
  geocoding: ^3.0.0
  timezone: ^0.9.2
  flutter_local_notifications: ^17.2.2
  cupertino_icons: ^1.0.6
  android_alarm_manager_plus: ^4.0.8
  intl: ^0.19.0
  
  # Use git version to avoid build issues with Flutter 3.29+

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
